-- Frontend
game:addlocalizedstring("MENU_SO_ACT_ALPHA", "ALPHA")
game:addlocalizedstring("MENU_SO_ACT_BRAVO", "BRAVO")
game:addlocalizedstring("MENU_SO_ACT_CHARLIE", "CHARLIE")
game:addlocalizedstring("MENU_SO_ACT_DELTA", "DELTA")
game:addlocalizedstring("MENU_SO_ACT_ECHO", "ECHO")

game:addlocalizedstring("MENU_SO_BEST_TIME", "Best Time: &&1")

game:addlocalizedstring("SPECIAL_OPS_DUMMY", "dummy")
game:addlocalizedstring("SPECIAL_OPS_DUMMY_DESC", "dummy")
game:addlocalizedstring("SPECIAL_OPS_TIME_NULL", "-:--.-")
game:addlocalizedstring("SPECIAL_OPS_TIME", "Time: ")
game:addlocalizedstring("SPECIAL_OPS_WAITING_P1", "Waiting for Player 1...")
game:addlocalizedstring("SPECIAL_OPS_WAITING_P2", "Waiting for Player 2...")
game:addlocalizedstring("SPECIAL_OPS_REVIVE_NAG_HINT", "Press ^3[{weapnext}]^7 to call your wingman.")
game:addlocalizedstring("SPECIAL_OPS_CHALLENGE_HURRY", "Hurry Up!")
game:addlocalizedstring("SPECIAL_OPS_CHALLENGE_SUCCESS", "Mission Success!")
game:addlocalizedstring("SPECIAL_OPS_CHALLENGE_FAILURE", "Mission Failed.")
game:addlocalizedstring("SPECIAL_OPS_FAILURE_HINT_TIME", "You ran out of time.\nKeep an eye on the clock.")
game:addlocalizedstring("SPECIAL_OPS_ESCAPE_WARNING", "Turn back and continue the mission!")
game:addlocalizedstring("SPECIAL_OPS_ESCAPE_MESSAGE", "Traitor. You have abandoned the mission.")
game:addlocalizedstring("SPECIAL_OPS_WAITING_OTHER_PLAYER", "Waiting for the other player...")
game:addlocalizedstring("SPECIAL_OPS_STARTING_IN", "Starting in: ")
game:addlocalizedstring("SPECIAL_OPS_UI_TIME", "Time")
game:addlocalizedstring("SPECIAL_OPS_UI_KILLS", "Kills")
game:addlocalizedstring("SPECIAL_OPS_UI_KILLS_OTHER", "Partner Kills")
game:addlocalizedstring("SPECIAL_OPS_UI_DIFFICULTY", "Difficulty")
game:addlocalizedstring("SPECIAL_OPS_UI_DIFFICULTY_OTHER", "Partner Difficulty")
game:addlocalizedstring("SPECIAL_OPS_UI_PLAY_AGAIN", "PLAY AGAIN ^0- ^3ESC^7")
game:addlocalizedstring("SPECIAL_OPS_UI_RETURN_TO_SPECIALOPS", "RETURN TO SPECIAL OPS")
game:addlocalizedstring("SPECIAL_OPS_UI_MISSION_FAILED", "MISSION FAILED")
game:addlocalizedstring("SPECIAL_OPS_UI_MISSION_SUCCESS", "Mission Success!")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_ALPHA", "Alpha")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_BETA", "Bravo")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_CHARLIE", "Charlie")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_DELTA", "Delta")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_ECHO", "Echo")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_ALPHA_CAPS", "ALPHA")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_BETA_CAPS", "BRAVO")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_CHARLIE_CAPS", "CHARLIE")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_DELTA_CAPS", "DELTA")
game:addlocalizedstring("SPECIAL_OPS_SO_BUTTON_ECHO_CAPS", "ECHO")
game:addlocalizedstring("SPECIAL_OPS_SO_HIDDEN_SO_GHILLIES", "Hidden")
game:addlocalizedstring("SPECIAL_OPS_SO_HIDDEN_SO_GHILLIES_DESC", "Evade enemy patrols and Ghillie Snipers near Chernobyl.")
game:addlocalizedstring("SPECIAL_OPS_SO_AC130_CO_HUNTED", "Overwatch")
game:addlocalizedstring("SPECIAL_OPS_SO_AC130_CO_HUNTED_DESC", "Rain death from above using an AC-130 gunship to protect your partner.")
game:addlocalizedstring("SPECIAL_OPS_SO_AC130_CO_HUNTED_OBJ_DESC", "Reach the Farm House basement.\nReach the western edge of the Workshops.\nReach the Barn near the Greenhouses.")
game:addlocalizedstring("SPECIAL_OPS_SO_CHOPPER_INVASION", "Big Brother")
game:addlocalizedstring("SPECIAL_OPS_SO_CHOPPER_INVASION_DESC", "Explosive ammunition, Vulcan Minigun, Blackhawk Helicopter.  Clear the way.")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_FAVELA", "O Cristo Redentor")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_FAVELA_DESC", "Hunt down and eliminate the Favela gang.  Minimize civilian casualties.")
game:addlocalizedstring("SPECIAL_OPS_SO_SNOWRACE1_CLIFFHANGER", "Race")
game:addlocalizedstring("SPECIAL_OPS_SO_SNOWRACE1_CLIFFHANGER_DESC", "Speed your snowmobile down the mountain, dodging trees, rocks and thousand foot drops.")
game:addlocalizedstring("SPECIAL_OPS_SO_SNOWRACE1_CLIFFHANGER_OBJ_DESC", "Finish in 2 minutes.\nFinish in 90 seconds.\nFinish in 70 seconds.")
game:addlocalizedstring("SPECIAL_OPS_SO_DEFUSE_FAVELA_ESCAPE", "Bomb Squad")
game:addlocalizedstring("SPECIAL_OPS_SO_DEFUSE_FAVELA_ESCAPE_DESC", "Race through the Favela marketplace defusing the explosives before its too late.")
game:addlocalizedstring("SPECIAL_OPS_SO_FOREST_CONTINGENCY", "Evasion")
game:addlocalizedstring("SPECIAL_OPS_SO_FOREST_CONTINGENCY_DESC", "Use silenced sniper rifles and cunning to slip past the enemy patrols.")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_INVASION", "Body Count")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_INVASION_DESC", "Rack up a large enough body count.  Quick kills earn larger bonuses.")
game:addlocalizedstring("SPECIAL_OPS_SO_ASSAULT_OILRIG", "Wetwork")
game:addlocalizedstring("SPECIAL_OPS_SO_ASSAULT_OILRIG_DESC", "Breach and clear two deadly rooms full of enemies and hostages to capture the oil rig.")
game:addlocalizedstring("SPECIAL_OPS_SO_DEMO_SO_BRIDGE", "Wreckage")
game:addlocalizedstring("SPECIAL_OPS_SO_DEMO_SO_BRIDGE_DESC", "Use C4, grenade launchers, RPGs, sentry guns, semtex and more to destroy every vehicle on the bridge.")
game:addlocalizedstring("SPECIAL_OPS_SO_SABOTAGE_CLIFFHANGER", "Acceptable Losses")
game:addlocalizedstring("SPECIAL_OPS_SO_SABOTAGE_CLIFFHANGER_DESC", "Sabotage the remote airbase with your silenced weapons and heartbeat sensor.")
game:addlocalizedstring("SPECIAL_OPS_SO_SHOWERS_GULAG", "Breach & Clear")
game:addlocalizedstring("SPECIAL_OPS_SO_SHOWERS_GULAG_DESC", "Smash through enemy defenses in the Gulag and escape.")
game:addlocalizedstring("SPECIAL_OPS_SO_TAKEOVER_OILRIG", "Armor Piercing")
game:addlocalizedstring("SPECIAL_OPS_SO_TAKEOVER_OILRIG_DESC", "Kill all fifteen Juggernauts on the oil rig.\nThis probably isn't even possible.")
game:addlocalizedstring("SPECIAL_OPS_SO_SNOWRACE2_CLIFFHANGER", "Time Trial")
game:addlocalizedstring("SPECIAL_OPS_SO_SNOWRACE2_CLIFFHANGER_DESC", "Launch your snowmobile across the chasm before time runs out.  Hit the flag gates to get extra time.")
game:addlocalizedstring("SPECIAL_OPS_SO_INTEL_BONEYARD", "Snatch & Grab")
game:addlocalizedstring("SPECIAL_OPS_SO_INTEL_BONEYARD_DESC", "Battle Shadow Company and Juggernauts in the airplane graveyard.  Grab the intel and escape to the extraction point.")
game:addlocalizedstring("SPECIAL_OPS_SO_ESCAPE_AIRPORT", "Terminal")
game:addlocalizedstring("SPECIAL_OPS_SO_ESCAPE_AIRPORT_DESC", "Pummel your way through enemy riot shield ambushes.")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_TRAINER", "The Pit")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_TRAINER_DESC", "Clear all of the enemy targets as fast as possible. Shooting civilians will prevent you from getting 3 stars.")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_TRAINER_OBJ_DESC", "Clear the course.\nClear in 45 seconds.\nClear in 35 Seconds.")
game:addlocalizedstring("SPECIAL_OPS_SO_JUGGERNAUTS_FAVELA", "High Explosive")
game:addlocalizedstring("SPECIAL_OPS_SO_JUGGERNAUTS_FAVELA_DESC", "Kill all ten Juggernauts using only explosives and a knife.  You'd be insane to even try this.")
game:addlocalizedstring("SPECIAL_OPS_SO_CROSSING_SO_BRIDGE", "Suspension")
game:addlocalizedstring("SPECIAL_OPS_SO_CROSSING_SO_BRIDGE_DESC", "Push through the invading forces on the bridge to reach the safe zone.")
game:addlocalizedstring("SPECIAL_OPS_SO_DEFENSE_INVASION", "Homeland Security")
game:addlocalizedstring("SPECIAL_OPS_SO_DEFENSE_INVASION_DESC", "Sentry guns, Thermal sights, Rocket launchers and Claymores.  Defend yourself from five difficult waves of attackers.")
game:addlocalizedstring("SPECIAL_OPS_SO_ROOFTOP_CONTINGENCY", "Sniper Fi")
game:addlocalizedstring("SPECIAL_OPS_SO_ROOFTOP_CONTINGENCY_DESC", "Use sniper rifles, claymores and Predator Drones to hold off waves of enemies.")
game:addlocalizedstring("SPECIAL_OPS_SO_DOWNLOAD_ARCADIA", "Wardriving")
game:addlocalizedstring("SPECIAL_OPS_SO_DOWNLOAD_ARCADIA_DESC", "Laze targets for the Stryker armored vehicle.  Battle in the 'burbs house to house, room to room.")
game:addlocalizedstring("SPECIAL_OPS_SO_TAKEOVER_ESTATE", "Estate Takedown")
game:addlocalizedstring("SPECIAL_OPS_SO_TAKEOVER_ESTATE_DESC", "Eliminate Ghillie Snipers, Elite Mercenaries and Juggernauts guarding the estate.")
game:addlocalizedstring("SPECIAL_OPS_SO_ALPHA_DESC", "Predator Drones, favela gangs, sniper rifles and stealth.  These Ops are short and sweet.")
game:addlocalizedstring("SPECIAL_OPS_SO_BETA_DESC", "AC-130 gunships, snowmobile races, and Vulcan miniguns with explosive ammo.  Something for everyone.")
game:addlocalizedstring("SPECIAL_OPS_SO_CHARLIE_DESC", "Time trials, explosive breaches, boneyards and enemies in Ghillie Suits.  Things are getting a bit tougher.")
game:addlocalizedstring("SPECIAL_OPS_SO_DELTA_DESC", "Blizzards, airports, estates and bridges.  Five challenging Ops.")
game:addlocalizedstring("SPECIAL_OPS_SO_ECHO_DESC", "An oil rig and a favela full of Juggernauts.  These Ops are fast and brutal.")
game:addlocalizedstring("SPECIAL_OPS_SO_BETA_UNLOCK_DESC", "Earn 4 stars to unlock.")
game:addlocalizedstring("SPECIAL_OPS_SO_CHARLIE_UNLOCK_DESC", "Earn 8 stars to unlock.")
game:addlocalizedstring("SPECIAL_OPS_SO_DELTA_UNLOCK_DESC", "Earn 20 stars to unlock.")
game:addlocalizedstring("SPECIAL_OPS_SO_ECHO_UNLOCK_DESC", "Earn 40 stars to unlock.")
game:addlocalizedstring("SPECIAL_OPS_SO_UNLOCK_DESC", "Earn stars to unlock.")
game:addlocalizedstring("SPECIAL_OPS_SO_BETA_UNLOCK_NOTICE", "Bravo Ops Unlocked!")
game:addlocalizedstring("SPECIAL_OPS_SO_CHARLIE_UNLOCK_NOTICE", "Charlie Ops Unlocked!")
game:addlocalizedstring("SPECIAL_OPS_SO_DELTA_UNLOCK_NOTICE", "Delta Ops Unlocked!")
game:addlocalizedstring("SPECIAL_OPS_SO_ECHO_UNLOCK_NOTICE", "Echo Ops Unlocked!")
game:addlocalizedstring("SPECIAL_OPS_SO_SELECT_AC130_GUNNER", "Select AC130 Gunner")
game:addlocalizedstring("SPECIAL_OPS_SO_SELECT_CHOPPER_GUNNER", "Select Chopper Gunner")
game:addlocalizedstring("SPECIAL_OPS_DASHDASH", "--")
game:addlocalizedstring("SPECIAL_OPS_HOSTILES", "Hostiles: ")
game:addlocalizedstring("SPECIAL_OPS_SO_KILLSPREE_FAVELA_OBJ_DESC", "30 Enemies, 6 Civilian casualties maximum.\n40 Enemies and Dogs, 4 Civilian casualties.\n50 Enemies and Dogs, 3 Civilian casualties.")
game:addlocalizedstring("SPECIAL_OPS_SO_ROOFTOP_CONTINGENCY_OBJ_DESC", "3 Waves of infantry, 1 Jeep and 1 Truck.\n4 Waves of infantry, 2 Jeeps and 1 Truck.\n5 Waves of infantry, 3 Jeeps and 2 Trucks.")
game:addlocalizedstring("SPECIAL_OPS_INTERMISSION_WAVENUM", "- Wave &&1 -")
game:addlocalizedstring("SPECIAL_OPS_INTERMISSION_WAVEFINAL", "- Final Wave -")
game:addlocalizedstring("SPECIAL_OPS_WAVENUM", "Wave: ")
game:addlocalizedstring("SPECIAL_OPS_WAVEFINAL", "Final Wave")
game:addlocalizedstring("SPECIAL_OPS_UI_KILLS_PARTNER", "Partner Kills")
game:addlocalizedstring("SPECIAL_OPS_PRESS_TO_START", "Press ^3[{+gostand}]^7 to set Ready.")
game:addlocalizedstring("SPECIAL_OPS_PRESS_TO_CANCEL", "Press ^3[{+stance}]^7 to set Not Ready.")
game:addlocalizedstring("SPECIAL_OPS_PLAYER_IS_NOT_READY", "&&1 is not ready.")
game:addlocalizedstring("SPECIAL_OPS_PLAYER_IS_READY", "&&1 is ready!")
game:addlocalizedstring("SPECIAL_OPS_ESCAPE_SPLASH", "Warning!")
game:addlocalizedstring("SPECIAL_OPS_EMPTY", " ")

game:addlocalizedstring("MENU_SP_TYPE_ASSAULT", "Assault")
game:addlocalizedstring("MENU_SP_TYPE_KILLSPREE", "Elimination")
game:addlocalizedstring("MENU_SP_TYPE_ESCORT", "Escort")
game:addlocalizedstring("MENU_SP_TYPE_WAVE_DEFENSE", "Wave Defense")
game:addlocalizedstring("MENU_SP_TYPE_TIME_ASSAULT", "Timed Assault")
game:addlocalizedstring("MENU_SP_TYPE_STEALTH", "Stealth")
game:addlocalizedstring("MENU_SP_TYPE_ASSAULT_DEFEND", "Assault & Defend")
game:addlocalizedstring("MENU_SP_TYPE_VEHICLE_KILLSPREE", "Vehicle Killspree")
game:addlocalizedstring("MENU_SP_TYPE_DRIVING", "Driving")

game:addlocalizedstring("MENU_SP_TYPE_TIMED_ESCORT", "Timed Escort")
game:addlocalizedstring("MENU_SP_NOTE_SLOW_MO_BREACH", "Slow-mo Breach")
game:addlocalizedstring("MENU_SP_NOTE_TWO_PLAYERS_REQUIRED", "Two Players Required")
game:addlocalizedstring("MENU_SP_NOTE_CIVILIAN", "Civilians")
game:addlocalizedstring("MENU_SP_NOTE_EXPLOSIVES_KNIVES_ONLY", "Explosives & Knives Only")

game:addlocalizedstring("MENU_SP_COMPLETION", "completion")
game:addlocalizedstring("MENU_SP_OPPOSITION_FORCE", "Est. Opposition:")

game:addlocalizedstring("MENU_SP_LEVEL_TYPE", "Classification: ")
game:addlocalizedstring("MENU_SP_LEVEL_AVG_TIME", "Est. Completion Time: ")
game:addlocalizedstring("MENU_SP_LEVEL_YOUR_BEST_TIME", "Your Best Time: ")
game:addlocalizedstring("MENU_SP_TYPE_TIMED_DRIVING", "Timed Driving")

game:addlocalizedstring("MENU_SP_DIFF_RANKING_0", "None")
game:addlocalizedstring("MENU_SP_DIFF_RANKING_1", "Minimal")
game:addlocalizedstring("MENU_SP_DIFF_RANKING_2", "Light")
game:addlocalizedstring("MENU_SP_DIFF_RANKING_3", "Medium")
game:addlocalizedstring("MENU_SP_DIFF_RANKING_4", "Heavy")
game:addlocalizedstring("MENU_SP_DIFF_RANKING_5", "Massive")

-- In Game
game:addlocalizedstring("SO_MISSION_SUCCESS", "Mission Success!")
game:addlocalizedstring("SO_MISSION_FAILED", "Mission Failed!")


